name: piano-recorder

services:
  recorder:
    build:
      context: https://github.com/TonistarNo1/piano-recorder.git#main
      dockerfile: Dockerfile
    container_name: piano-recorder-server
    restart: unless-stopped
    ports:
      - "5052:5051" # falls 5051 frei ist, kannst du "5051:5051" nehmen
    environment:
      RECORD_ROOT: /mnt/ssd/piano
      ARCHIVE_ROOT: /mnt/ssd/archive
      STATE_ROOT: /mnt/ssd/state
      LOG_ROOT: /mnt/ssd/logs
    
      VIDEO_DEVICE: /dev/video0
      AUDIO_DEVICE: plughw:1
    
      VIDEO_WIDTH: "1920"
      VIDEO_HEIGHT: "1080"
      VIDEO_FPS: "30"
      AUDIO_RATE: "48000"
    
      VIDEO_THREAD_QUEUE_SIZE: "16384"
      AUDIO_THREAD_QUEUE_SIZE: "32768"
      VIDEO_RTBUF_SIZE: "512M"

      RECORD_MASTER_WAV_LIVE: "0"
      CREATE_AUDIO_MIX: "0"
    
      X264_PRESET: ultrafast
      X264_CRF: "22"
      ENCODER_PREFERENCE: libx264
    
      RETENTION_DAYS: "14"
    volumes:
      - /mnt/ssd:/mnt/ssd
    devices:
      - /dev/video0:/dev/video0
      - /dev/snd:/dev/snd
      - /dev/dri:/dev/dri
    command: ["python", "/app/server.py"]

  archiver:
    build:
      context: https://github.com/TonistarNo1/piano-recorder.git#main
      dockerfile: Dockerfile
    container_name: piano-recorder-archiver
    restart: unless-stopped
    environment:
      RECORD_ROOT: /mnt/ssd/piano
      ARCHIVE_ROOT: /mnt/ssd/archive
      STATE_ROOT: /mnt/ssd/state
      LOG_ROOT: /mnt/ssd/logs
      RETENTION_DAYS: "14"
      ARCHIVE_CHECK_SECONDS: "86400"
    volumes:
      - /mnt/ssd:/mnt/ssd
    command: ["python", "/app/archive_worker.py"]
